version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9094:9094
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "twitter:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  tweet-producer:
    image: kafka-producer:latest
    build: ./kafka-producer
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - kafka

  # tweet-consumer:
  #   image: kafka-consumer-1:latest
  #   build: ./kafka-consumer-realtime
  #   ports:
  #    - "8081:8081"
  #   tty: true
  #   depends_on:
  #    - kafka
