version: '3.5'

networks:
  twitter-inappropriate-language-detection:
    external: false
    name : twitter-inappropriate-language-detection

services:
  cassandra:
    image: 'bitnami/cassandra:latest'
    ports:
      - '7000:7000'
      - '9042:9042'
    container_name: cassandra
    restart: always
    environment:
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - twitter-inappropriate-language-detection
    volumes:
      - './cassandra_persistence:/bitnami'

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
    container_name: zookeeper
    networks:
      - twitter-inappropriate-language-detection

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9094:9094
    networks:
      - twitter-inappropriate-language-detection
    restart: always
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "twitter:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  tweet-producer:
    image: kafka-producer:latest
    build:
      ./kafka-producer
      # context: ./
      # dockerfile: ./kafka-producer/Dockerfile
    ports:
      - "8080:8080"
    container_name: kafka-producer
    tty: true
    restart: always
    networks:
      - twitter-inappropriate-language-detection
    depends_on:
      - kafka

  tweet-consumer-1:
    image: kafka-consumer-1:latest
    build:
      context: ./
      dockerfile: ./kafka-consumer-realtime/Dockerfile
    ports:
     - "8081:8081"
    container_name: kafka-consumer-1
    tty: true
    restart: always
    networks:
      - twitter-inappropriate-language-detection
    depends_on:
     - kafka
