version: '3.5'

networks:
  twitter-inappropriate-language-detection:
    external: false
    name : twitter-inappropriate-language-detection

services:
  cassandra:
    image: 'bitnami/cassandra:latest'
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7191:7191'
      - '9042:9042'
      - '9160:9160'
    container_name: cassandra
    restart: always
    environment:
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_TRANSPORT_PORT_NUMBER=7000
      - CASSANDRA_CQL_PORT_NUMBER=9042
      - CASSANDRA_HOST=cassandra
    networks:
      - twitter-inappropriate-language-detection
    volumes:
      - './cassandra_persistence:/bitnami'
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
    container_name: zookeeper
    networks:
      - twitter-inappropriate-language-detection

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9094:9094
    networks:
      - twitter-inappropriate-language-detection
    restart: always
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "twitter:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  tweet-producer:
    image: kafka-producer:latest
    build:
      ./kafka-producer
      # context: ./
      # dockerfile: ./kafka-producer/Dockerfile
    ports:
      - "8080:8080"
    container_name: kafka-producer
    tty: true
    restart: always
    networks:
      - twitter-inappropriate-language-detection
    depends_on:
      - kafka

  tweet-consumer-1:
    image: kafka-consumer-1:latest
    build:
      context: ./
      dockerfile: ./kafka-consumer-realtime/Dockerfile
    ports:
     - "8081:8081"
    container_name: kafka-consumer-1
    tty: true
    restart: always
    networks:
      - twitter-inappropriate-language-detection
    depends_on:
     - kafka

  tweet-consumer-2:
    image: kafka-consumer-2:latest
    build:
      context: ./
      dockerfile: ./kafka-consumer-cassandra/Dockerfile
    ports:
     - "8082:8082"
    container_name: kafka-consumer-2
    tty: true
    restart: always
    networks:
      - twitter-inappropriate-language-detection
    depends_on:
     - kafka
     - cassandra

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - twitter-inappropriate-language-detection
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
volumes:
  portainer_data: